baseURL: 'https://subhashhalder.com/'
languageCode: en-us
title: Subhash Halder
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true
googleAnalytics: G-JKJTS285E8
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: Subhash Halder | Full-Stack Software Engineer
  description: >-
    Hello World!! My name is Subhash Halder and I am a Full-Stack Software
    Engineer
  keywords:
    - Blog
    - Portfolio
    - PaperMod
    - Subhash Halder
    - Software Engineer
    - Engineer for hire
    - Ready for hire
  author: Subhash Halder
  images:
    - /images/subhash_halder_350_350.jpg
  DateFormat: 'January 2, 2006'
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    favicon: /images/subhash_halder_350_350.jpg
    favicon16x16: /images/subhash_halder_16_16.jpg
    favicon32x32: /images/subhash_halder_35_35.jpg
    apple_touch_icon: /images/subhash_halder_350_350.jpg
    safari_pinned_tab: /images/subhash_halder_350_350.jpg
  label:
    text: Subhash Halder
    icon: /images/subhash_halder_120_120.jpg
    iconHeight: 35
  profileMode:
    enabled: false
    title: Subhash Halder
    subtitle: >-
      Hello World!! My name is Subhash Halder and I am a Full-Stack Software
      Engineer
    imageUrl: /images/subhash_halder_120_120.jpg
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: My name is Subhash Halder and I am a Full Stack Software Engineer.
  socialIcons:
    - name: github
      url: 'https://github.com/amsubhash'
    - name: linkedin
      url: 'https://www.linkedin.com/in/amsubhash/'
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  editPost:
    URL: 'https://github.com/amsubhash/blog/blob/main/content'
    Text: Suggest Changes
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
